### ISSUE TITLE
编译错误 Class not found: org.jboss.vfs.VFS

### ISSUE THREAD

**Issue by lanyuanxiaoyao** [itfsw/mybatis-generator-plugin#79]
我希望自己添加新的插件的时候, 在测试时报如下错误, 我使用的数据库为h2, 标准sql
```
13:48:02.839 [main] DEBUG org.mybatis.generator.logging.LogFactory - Logging initialized using 'org.mybatis.generator.logging.slf4j.Slf4jLoggingLogFactory@71a794e5' adapter.
13:48:02.886 [main] DEBUG org.mybatis.generator.internal.db.DatabaseIntrospector - Retrieving column information for table "PUBLIC.FUND"
13:48:02.980 [main] DEBUG org.mybatis.generator.internal.db.DatabaseIntrospector - Found column "ID", data type -5, in table "FUND.PUBLIC.FUND"
13:48:02.996 [main] DEBUG org.mybatis.generator.internal.db.DatabaseIntrospector - Found column "CODE", data type 12, in table "FUND.PUBLIC.FUND"
13:48:02.996 [main] DEBUG org.mybatis.generator.internal.db.DatabaseIntrospector - Found column "CREATE_TIME", data type 93, in table "FUND.PUBLIC.FUND"
13:48:02.996 [main] DEBUG org.mybatis.generator.internal.db.DatabaseIntrospector - Found column "DESCRIPTION", data type 12, in table "FUND.PUBLIC.FUND"
13:48:02.996 [main] DEBUG org.mybatis.generator.internal.db.DatabaseIntrospector - Found column "NAME", data type 12, in table "FUND.PUBLIC.FUND"
13:48:02.996 [main] DEBUG org.mybatis.generator.internal.db.DatabaseIntrospector - Found column "UPDATE_TIME", data type 93, in table "FUND.PUBLIC.FUND"
13:48:03.952 [main] DEBUG com.itfsw.mybatis.generator.plugins.utils.BasePlugin - 使用实体组合查询方法
13:48:06.909 [main] DEBUG org.apache.ibatis.logging.LogFactory - Logging initialized using 'class org.apache.ibatis.logging.slf4j.Slf4jImpl' adapter.
13:48:06.909 [main] DEBUG org.apache.ibatis.io.VFS - Class not found: org.jboss.vfs.VFS
13:48:06.909 [main] DEBUG org.apache.ibatis.io.JBoss6VFS - JBoss 6 VFS API is not available in this environment.
13:48:06.909 [main] DEBUG org.apache.ibatis.io.VFS - Class not found: org.jboss.vfs.VirtualFile
13:48:06.909 [main] DEBUG org.apache.ibatis.io.VFS - VFS implementation org.apache.ibatis.io.JBoss6VFS is not valid in this environment.
13:48:06.909 [main] DEBUG org.apache.ibatis.io.VFS - Using VFS adapter org.apache.ibatis.io.DefaultVFS
13:48:06.909 [main] DEBUG org.apache.ibatis.io.DefaultVFS - Find JAR URL: file:/C:/Users/lanyu/IdeaProjects/mybatis-generator-plugin/target/test-classes/com/itfsw/mybatis/generator/plugins/dao/s20190405134802046
13:48:06.909 [main] DEBUG org.apache.ibatis.io.DefaultVFS - Not a JAR: file:/C:/Users/lanyu/IdeaProjects/mybatis-generator-plugin/target/test-classes/com/itfsw/mybatis/generator/plugins/dao/s20190405134802046
13:48:06.956 [main] DEBUG org.apache.ibatis.io.DefaultVFS - Reader entry: Fund.class
13:48:06.956 [main] DEBUG org.apache.ibatis.io.DefaultVFS - Reader entry: Fund.java
13:48:06.956 [main] DEBUG org.apache.ibatis.io.DefaultVFS - Reader entry: FundMapper.class
13:48:06.956 [main] DEBUG org.apache.ibatis.io.DefaultVFS - Reader entry: FundMapper.java
13:48:06.956 [main] DEBUG org.apache.ibatis.io.DefaultVFS - Reader entry: FundMapper.xml
13:48:06.956 [main] DEBUG org.apache.ibatis.io.DefaultVFS - Listing file:/C:/Users/lanyu/IdeaProjects/mybatis-generator-plugin/target/test-classes/com/itfsw/mybatis/generator/plugins/dao/s20190405134802046
13:48:06.956 [main] DEBUG org.apache.ibatis.io.DefaultVFS - Find JAR URL: file:/C:/Users/lanyu/IdeaProjects/mybatis-generator-plugin/target/test-classes/com/itfsw/mybatis/generator/plugins/dao/s20190405134802046/Fund.class
13:48:06.956 [main] DEBUG org.apache.ibatis.io.DefaultVFS - Not a JAR: file:/C:/Users/lanyu/IdeaProjects/mybatis-generator-plugin/target/test-classes/com/itfsw/mybatis/generator/plugins/dao/s20190405134802046/Fund.class
13:48:06.956 [main] DEBUG org.apache.ibatis.io.DefaultVFS - Reader entry: ����   4 <
13:48:06.956 [main] DEBUG org.apache.ibatis.io.DefaultVFS - Find JAR URL: file:/C:/Users/lanyu/IdeaProjects/mybatis-generator-plugin/target/test-classes/com/itfsw/mybatis/generator/plugins/dao/s20190405134802046/Fund.java
13:48:06.956 [main] DEBUG org.apache.ibatis.io.DefaultVFS - Not a JAR: file:/C:/Users/lanyu/IdeaProjects/mybatis-generator-plugin/target/test-classes/com/itfsw/mybatis/generator/plugins/dao/s20190405134802046/Fund.java
13:48:06.971 [main] DEBUG org.apache.ibatis.io.DefaultVFS - Reader entry: package com.itfsw.mybatis.generator.plugins.dao.s20190405134802046;
13:48:06.971 [main] DEBUG org.apache.ibatis.io.DefaultVFS - Find JAR URL: file:/C:/Users/lanyu/IdeaProjects/mybatis-generator-plugin/target/test-classes/com/itfsw/mybatis/generator/plugins/dao/s20190405134802046/FundMapper.class
13:48:06.971 [main] DEBUG org.apache.ibatis.io.DefaultVFS - Not a JAR: file:/C:/Users/lanyu/IdeaProjects/mybatis-generator-plugin/target/test-classes/com/itfsw/mybatis/generator/plugins/dao/s20190405134802046/FundMapper.class
13:48:06.971 [main] DEBUG org.apache.ibatis.io.DefaultVFS - Reader entry: ����   4    deleteByPrimaryKey (Ljava/lang/Long;)I insert D(Lcom/itfsw/mybatis/generator/plugins/dao/s20190405134802046/Fund;)I insertSelective selectByPrimaryKey S(Ljava/lang/Long;)Lcom/itfsw/mybatis/generator/plugins/dao/s20190405134802046/Fund; updateByPrimaryKeySelective updateByPrimaryKey 
13:48:06.971 [main] DEBUG org.apache.ibatis.io.DefaultVFS - Find JAR URL: file:/C:/Users/lanyu/IdeaProjects/mybatis-generator-plugin/target/test-classes/com/itfsw/mybatis/generator/plugins/dao/s20190405134802046/FundMapper.java
13:48:06.971 [main] DEBUG org.apache.ibatis.io.DefaultVFS - Not a JAR: file:/C:/Users/lanyu/IdeaProjects/mybatis-generator-plugin/target/test-classes/com/itfsw/mybatis/generator/plugins/dao/s20190405134802046/FundMapper.java
13:48:06.971 [main] DEBUG org.apache.ibatis.io.DefaultVFS - Reader entry: package com.itfsw.mybatis.generator.plugins.dao.s20190405134802046;
13:48:06.971 [main] DEBUG org.apache.ibatis.io.DefaultVFS - Find JAR URL: file:/C:/Users/lanyu/IdeaProjects/mybatis-generator-plugin/target/test-classes/com/itfsw/mybatis/generator/plugins/dao/s20190405134802046/FundMapper.xml
13:48:06.971 [main] DEBUG org.apache.ibatis.io.DefaultVFS - Not a JAR: file:/C:/Users/lanyu/IdeaProjects/mybatis-generator-plugin/target/test-classes/com/itfsw/mybatis/generator/plugins/dao/s20190405134802046/FundMapper.xml
13:48:06.971 [main] DEBUG org.apache.ibatis.io.DefaultVFS - Reader entry: <?xml version="1.0" encoding="UTF-8"?>
13:48:06.971 [main] DEBUG org.apache.ibatis.io.ResolverUtil - Checking to see if class com.itfsw.mybatis.generator.plugins.dao.s20190405134802046.Fund matches criteria [is assignable to Object]
13:48:06.971 [main] DEBUG org.apache.ibatis.io.ResolverUtil - Checking to see if class com.itfsw.mybatis.generator.plugins.dao.s20190405134802046.FundMapper matches criteria [is assignable to Object]
13:48:07.124 [main] DEBUG org.apache.ibatis.datasource.pooled.PooledDataSource - PooledDataSource forcefully closed/removed all connections.
13:48:07.124 [main] DEBUG org.apache.ibatis.datasource.pooled.PooledDataSource - PooledDataSource forcefully closed/removed all connections.
13:48:07.124 [main] DEBUG org.apache.ibatis.datasource.pooled.PooledDataSource - PooledDataSource forcefully closed/removed all connections.
13:48:07.124 [main] DEBUG org.apache.ibatis.datasource.pooled.PooledDataSource - PooledDataSource forcefully closed/removed all connections.
java.lang.ClassNotFoundException: com.itfsw.mybatis.generator.plugins.dao.s20190405134802046.TbMapper
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:817)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.itfsw.mybatis.generator.plugins.SelectByModelPluginTest$1.reloadProject(SelectByModelPluginTest.java:26)
	at com.itfsw.mybatis.generator.plugins.tools.AbstractShellCallback.refreshProject(AbstractShellCallback.java:57)
	at org.mybatis.generator.api.MyBatisGenerator.generate(MyBatisGenerator.java:289)
	at com.itfsw.mybatis.generator.plugins.tools.MyBatisGeneratorTool.generate(MyBatisGeneratorTool.java:95)
	at com.itfsw.mybatis.generator.plugins.tools.MyBatisGeneratorTool.generate(MyBatisGeneratorTool.java:108)
	at com.itfsw.mybatis.generator.plugins.SelectByModelPluginTest.testCreateMethod(SelectByModelPluginTest.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.itfsw.mybatis.generator.plugins.tools.AbstractShellCallback.refreshProject(AbstractShellCallback.java:60)
	at org.mybatis.generator.api.MyBatisGenerator.generate(MyBatisGenerator.java:289)
	at com.itfsw.mybatis.generator.plugins.tools.MyBatisGeneratorTool.generate(MyBatisGeneratorTool.java:95)
	at com.itfsw.mybatis.generator.plugins.tools.MyBatisGeneratorTool.generate(MyBatisGeneratorTool.java:108)
	at com.itfsw.mybatis.generator.plugins.SelectByModelPluginTest.testCreateMethod(SelectByModelPluginTest.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by itfsw** [comment]
看报错应该是你h2的相关依赖报错了
